theme: jekyll-theme-hacker
lang: es_MX
timezone: America/Cancun
title: WebDeveloperHints
description: Notas sobre desarrollo, programación, marketing digital y tecnología
url: https://webdeveloperhints.com
author:
  twitter: lgzarturo
tag_manager: GTM-53H37XV
show_downloads: false
feed:
  excerpt_only: true
  tags: true

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
